language: rust
env: FEATURES=""
matrix:
  fast_finish: true
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: nightly
    env: FEATURES="ordered-multimap"
  allow_failures:
  - rust: nightly
    env: FEATURES="ordered-multimap"
script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"
